# Generated by Django 5.2.9 on 2026-03-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_unaccent_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_rejection_reason',
            field=models.TextField(blank=True, verbose_name='external rejection reason'),
        ),
        migrations.AddField(
            model_name='user',
            name='external_validation_status',
            field=models.CharField(choices=[('none', 'Non applicable'), ('pending', 'En attente de validation'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='none', max_length=10, verbose_name='external validation status'),
        ),
    ]
