# Generated by Django 5.2.9 on 2026-03-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_external_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cas_username',
            field=models.CharField(blank=True, help_text='The CAS username (e.g., e12345678).', max_length=255, null=True, unique=True, verbose_name='CAS username'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_cas_user',
            field=models.BooleanField(default=False, help_text='Whether this user authenticated via CAS SSO.', verbose_name='CAS user'),
        ),
    ]
