# Generated by Django 5.2.9 on 2026-01-26 22:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tasks', models.JSONField(blank=True, default=list)),
                ('language', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('min_person', models.PositiveIntegerField(blank=True, null=True)),
                ('max_person', models.PositiveIntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ManyToManyField(blank=True, related_name='authored_projects', to=settings.AUTH_USER_MODEL)),
                ('externes', models.ManyToManyField(blank=True, related_name='external_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
