# Generated by Django 5.2.9 on 2025-12-16 11:33

import backend_django.projects.models
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProject',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=500, verbose_name='subject')),
                ('project_type', models.CharField(choices=[('memoir', 'Mémoire'), ('internship', 'Stage'), ('srw', 'T.E.R.')], max_length=20, verbose_name='type')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
            ],
            options={
                'verbose_name': 'academic project',
                'verbose_name_plural': 'academic projects',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=backend_django.projects.models.attachment_path, verbose_name='file')),
                ('original_filename', models.CharField(max_length=255, verbose_name='original filename')),
                ('content_type', models.CharField(max_length=100, verbose_name='content type')),
                ('size', models.PositiveIntegerField(help_text='Size in bytes', verbose_name='file size')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
                'ordering': ['-created'],
            },
        ),
    ]
