# Generated by Django 5.2.9 on 2025-12-16 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicproject',
            name='referent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_referent', to=settings.AUTH_USER_MODEL, verbose_name='referent'),
        ),
        migrations.AddField(
            model_name='academicproject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_as_student', to=settings.AUTH_USER_MODEL, verbose_name='student'),
        ),
        migrations.AddField(
            model_name='academicproject',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='supervisor'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='academicproject',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='academic_projects', to='projects.attachment', verbose_name='files'),
        ),
    ]
