# Generated by Django 5.2.9 on 2026-01-26 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('ter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='ter.ter'),
        ),
    ]
