# Generated by Django 5.2.9 on 2026-01-09 08:00

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicproject',
            name='academic_year',
            field=models.CharField(blank=True, max_length=9, verbose_name='academic year'),
        ),
        migrations.AddField(
            model_name='academicproject',
            name='admin_validated',
            field=models.BooleanField(default=False, verbose_name='administratively validated'),
        ),
        migrations.AddField(
            model_name='academicproject',
            name='admin_validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='admin validation date'),
        ),
        migrations.AddField(
            model_name='academicproject',
            name='admin_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_validated_projects', to=settings.AUTH_USER_MODEL, verbose_name='validated by'),
        ),
        migrations.AddField(
            model_name='academicproject',
            name='company_address',
            field=models.TextField(blank=True, verbose_name='company address'),
        ),
        migrations.AddField(
            model_name='academicproject',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='company name'),
        ),
        migrations.AddField(
            model_name='academicproject',
            name='company_tutor_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='company tutor email'),
        ),
        migrations.AddField(
            model_name='academicproject',
            name='company_tutor_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='company tutor name'),
        ),
        migrations.AddField(
            model_name='academicproject',
            name='company_tutor_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='company tutor phone'),
        ),
        migrations.AddField(
            model_name='academicproject',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='academicproject',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de validation'), ('validated', 'Validé'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('archived', 'Archivé'), ('rejected', 'Refusé')], default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('project_type', models.CharField(choices=[('memoir', 'Mémoire'), ('internship', 'Stage'), ('srw', 'T.E.R.')], max_length=20, verbose_name='type')),
                ('status', models.CharField(choices=[('open', 'Ouvert aux candidatures'), ('assigned', 'Attribué'), ('in_development', 'En cours de définition'), ('closed', 'Clôturé')], default='open', max_length=20, verbose_name='status')),
                ('academic_year', models.CharField(max_length=9, verbose_name='academic year')),
                ('is_professor_proposal', models.BooleanField(default=True, verbose_name='professor proposal')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_proposals', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('resulting_project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_proposal', to='projects.academicproject', verbose_name='resulting project')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_proposals', to=settings.AUTH_USER_MODEL, verbose_name='supervisor')),
            ],
            options={
                'verbose_name': 'proposal',
                'verbose_name_plural': 'proposals',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProposalApplication',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivation', models.TextField(blank=True, verbose_name='motivation')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], default='pending', max_length=20, verbose_name='status')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_applications', to=settings.AUTH_USER_MODEL, verbose_name='applicant')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projects.proposal', verbose_name='proposal')),
            ],
            options={
                'verbose_name': 'proposal application',
                'verbose_name_plural': 'proposal applications',
                'ordering': ['-created'],
                'constraints': [models.UniqueConstraint(fields=('proposal', 'applicant'), name='unique_proposal_application')],
            },
        ),
    ]
