# Generated by Django 5.2.9 on 2026-01-25 16:05

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_academicproject_academic_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StagePeriod',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'Stage M2 2024-2025'", max_length=200, verbose_name='name')),
                ('academic_year', models.CharField(help_text='Format: 2024-2025', max_length=9, verbose_name='academic year')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('open', 'Ouvert'), ('closed', 'Clôturé'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='status')),
                ('offer_submission_start', models.DateField(help_text='Date when companies can start submitting offers', verbose_name='offer submission start')),
                ('offer_submission_end', models.DateField(help_text='Deadline for offer submissions', verbose_name='offer submission end')),
                ('application_start', models.DateField(help_text='Date when students can start applying', verbose_name='application start')),
                ('application_end', models.DateField(help_text='Deadline for applications', verbose_name='application end')),
                ('internship_start', models.DateField(help_text='Start date for internships', verbose_name='internship start')),
                ('internship_end', models.DateField(help_text='End date for internships', verbose_name='internship end')),
            ],
            options={
                'verbose_name': 'internship period',
                'verbose_name_plural': 'internship periods',
                'ordering': ['-academic_year', '-created'],
            },
        ),
        migrations.CreateModel(
            name='TERPeriod',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'TER 2024-2025 S1'", max_length=200, verbose_name='name')),
                ('academic_year', models.CharField(help_text='Format: 2024-2025', max_length=9, verbose_name='academic year')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('open', 'Ouvert'), ('closed', 'Clôturé'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='status')),
                ('group_formation_start', models.DateField(help_text='Date when students can start forming groups', verbose_name='group formation start')),
                ('group_formation_end', models.DateField(help_text='Deadline for group formation', verbose_name='group formation end')),
                ('subject_selection_start', models.DateField(help_text='Date when groups can start selecting subjects', verbose_name='subject selection start')),
                ('subject_selection_end', models.DateField(help_text='Deadline for subject selection/ranking', verbose_name='subject selection end')),
                ('assignment_date', models.DateField(help_text='Date when algorithm runs to assign subjects', verbose_name='assignment date')),
                ('project_start', models.DateField(help_text='Start date for TER projects', verbose_name='project start')),
                ('project_end', models.DateField(help_text='End date for TER projects', verbose_name='project end')),
                ('min_group_size', models.PositiveSmallIntegerField(default=1, verbose_name='minimum group size')),
                ('max_group_size', models.PositiveSmallIntegerField(default=4, verbose_name='maximum group size')),
            ],
            options={
                'verbose_name': 'TER period',
                'verbose_name_plural': 'TER periods',
                'ordering': ['-academic_year', '-created'],
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Group name chosen by the leader', max_length=200, verbose_name='name')),
                ('status', django_fsm.FSMField(choices=[('ouvert', 'Ouvert'), ('forme', 'Formé'), ('cloture', 'Clôturé')], default='ouvert', max_length=50, protected=True, verbose_name='status')),
                ('project_type', models.CharField(choices=[('memoir', 'Mémoire'), ('internship', 'Stage'), ('srw', 'T.E.R.')], help_text='TER or Stage', max_length=20, verbose_name='project type')),
                ('assigned_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_groups', to='projects.proposal', verbose_name='assigned proposal')),
                ('leader', models.ForeignKey(help_text='The student who created and leads the group', on_delete=django.db.models.deletion.CASCADE, related_name='led_groups', to=settings.AUTH_USER_MODEL, verbose_name='leader')),
                ('members', models.ManyToManyField(help_text='All group members including the leader', related_name='student_groups', to=settings.AUTH_USER_MODEL, verbose_name='members')),
                ('stage_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='projects.stageperiod', verbose_name='internship period')),
                ('ter_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='projects.terperiod', verbose_name='TER period')),
            ],
            options={
                'verbose_name': 'student group',
                'verbose_name_plural': 'student groups',
                'ordering': ['-created'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('stage_period__isnull', True), ('ter_period__isnull', False)), models.Q(('stage_period__isnull', False), ('ter_period__isnull', True)), _connector='OR'), name='group_period_exclusive')],
            },
        ),
    ]
