# Generated by Django 5.2.9 on 2026-01-26 07:14

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_add_periods_and_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('declined', 'Refusée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='status')),
                ('message', models.TextField(blank=True, help_text='Optional message from the leader', verbose_name='message')),
                ('responded_at', models.DateTimeField(blank=True, help_text='When the invitee responded', null=True, verbose_name='responded at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='projects.studentgroup', verbose_name='group')),
                ('invited_by', models.ForeignKey(help_text='The leader who sent the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='invited by')),
                ('invitee', models.ForeignKey(help_text='The student being invited', on_delete=django.db.models.deletion.CASCADE, related_name='group_invitations', to=settings.AUTH_USER_MODEL, verbose_name='invitee')),
            ],
            options={
                'verbose_name': 'group invitation',
                'verbose_name_plural': 'group invitations',
                'ordering': ['-created'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('group', 'invitee'), name='unique_pending_invitation')],
            },
        ),
    ]
