# Generated by Django 5.2.9 on 2026-03-01 17:40

import backend_django.chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=backend_django.chat.models.chat_file_path,
            ),
        ),
        migrations.AddField(
            model_name='message',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
