# Generated by Django 5.2.9 on 2026-01-27 10:25

import django.utils.timezone
import django_fsm
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Group name chosen by the leader', max_length=200, verbose_name='name')),
                ('status', django_fsm.FSMField(choices=[('ouvert', 'Ouvert'), ('forme', 'Forme'), ('cloture', 'Cloture')], default='ouvert', max_length=50, protected=True, verbose_name='status')),
                ('project_type', models.CharField(help_text='TER or Stage', max_length=20, verbose_name='project type')),
            ],
            options={
                'verbose_name': 'student group',
                'verbose_name_plural': 'student groups',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptee'), ('declined', 'Refusee'), ('cancelled', 'Annulee')], default='pending', max_length=20, verbose_name='status')),
                ('message', models.TextField(blank=True, help_text='Optional message from the leader', verbose_name='message')),
                ('responded_at', models.DateTimeField(blank=True, help_text='When the invitee responded', null=True, verbose_name='responded at')),
            ],
            options={
                'verbose_name': 'group invitation',
                'verbose_name_plural': 'group invitations',
                'ordering': ['-created'],
            },
        ),
    ]
