# Generated by Django 5.2.9 on 2026-01-27 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('stages', '0001_initial'),
        ('ter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='assigned_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_groups', to='ter.tersubject', verbose_name='assigned subject'),
        ),
        migrations.AddField(
            model_name='group',
            name='leader',
            field=models.ForeignKey(help_text='The student who created and leads the group', on_delete=django.db.models.deletion.CASCADE, related_name='led_groups', to=settings.AUTH_USER_MODEL, verbose_name='leader'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(help_text='All group members including the leader', related_name='student_groups', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
        migrations.AddField(
            model_name='group',
            name='stage_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='stages.stageperiod', verbose_name='internship period'),
        ),
        migrations.AddField(
            model_name='group',
            name='ter_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='ter.terperiod', verbose_name='TER period'),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='groups.group', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='invited_by',
            field=models.ForeignKey(help_text='The leader who sent the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='invited by'),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='invitee',
            field=models.ForeignKey(help_text='The student being invited', on_delete=django.db.models.deletion.CASCADE, related_name='group_invitations', to=settings.AUTH_USER_MODEL, verbose_name='invitee'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stage_period__isnull', True), ('ter_period__isnull', False)), models.Q(('stage_period__isnull', False), ('ter_period__isnull', True)), _connector='OR'), name='group_period_exclusive'),
        ),
        migrations.AddConstraint(
            model_name='groupinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('group', 'invitee'), name='unique_pending_invitation'),
        ),
    ]
