# Generated by Django 5.2.9 on 2026-02-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_add_assigned_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='max_group_size',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of members allowed in this group. Null means unlimited.', null=True, verbose_name='maximum group size'),
        ),
    ]
