# Generated by Django 5.2.9 on 2026-02-15 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_max_group_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Migration kept empty - leader field stays as CASCADE (not SET_NULL)
        # Vincent's original change reverted: groups must always have a leader
    ]
