# Generated by Django 5.2.9 on 2026-01-27 10:25

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StagePeriod',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'Stage M2 2024-2025'", max_length=200, verbose_name='name')),
                ('academic_year', models.CharField(help_text='Format: 2024-2025', max_length=9, verbose_name='academic year')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('open', 'Ouvert'), ('closed', 'Cloture'), ('archived', 'Archive')], default='draft', max_length=20, verbose_name='status')),
                ('offer_submission_start', models.DateField(help_text='Date when companies can start submitting offers', verbose_name='offer submission start')),
                ('offer_submission_end', models.DateField(help_text='Deadline for offer submissions', verbose_name='offer submission end')),
                ('application_start', models.DateField(help_text='Date when students can start applying', verbose_name='application start')),
                ('application_end', models.DateField(help_text='Deadline for applications', verbose_name='application end')),
                ('internship_start', models.DateField(help_text='Start date for internships', verbose_name='internship start')),
                ('internship_end', models.DateField(help_text='End date for internships', verbose_name='internship end')),
            ],
            options={
                'verbose_name': 'internship period',
                'verbose_name_plural': 'internship periods',
                'ordering': ['-academic_year', '-created'],
            },
        ),
        migrations.CreateModel(
            name='StageOffer',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('company_name', models.CharField(max_length=255, verbose_name='company name')),
                ('location', models.CharField(blank=True, help_text='City or remote', max_length=255, verbose_name='location')),
                ('domain', models.CharField(help_text="e.g., 'IA/ML', 'Securite', 'Web', 'DevOps'", max_length=100, verbose_name='domain')),
                ('prerequisites', models.TextField(blank=True, help_text='Required skills or knowledge', verbose_name='prerequisites')),
                ('max_students', models.PositiveSmallIntegerField(default=1, help_text='Number of students that can be assigned', verbose_name='maximum students')),
                ('status', django_fsm.FSMField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('validated', 'Valide'), ('rejected', 'Rejete')], default='draft', max_length=50, verbose_name='status')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_offers_created', to=settings.AUTH_USER_MODEL, verbose_name='supervisor')),
                ('stage_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='stages.stageperiod', verbose_name='internship period')),
            ],
            options={
                'verbose_name': 'internship offer',
                'verbose_name_plural': 'internship offers',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='StageFavorite',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_favorites', to=settings.AUTH_USER_MODEL, verbose_name='student')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='stages.stageoffer', verbose_name='offer')),
            ],
            options={
                'verbose_name': 'internship favorite',
                'verbose_name_plural': 'internship favorites',
                'constraints': [models.UniqueConstraint(fields=('student', 'offer'), name='unique_stage_student_favorite')],
            },
        ),
        migrations.CreateModel(
            name='StageRanking',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.PositiveSmallIntegerField(help_text='1 = most preferred', verbose_name='rank')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='stages.stageoffer', verbose_name='offer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_rankings', to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
            options={
                'verbose_name': 'internship ranking',
                'verbose_name_plural': 'internship rankings',
                'ordering': ['student', 'rank'],
                'constraints': [models.UniqueConstraint(fields=('student', 'offer'), name='unique_stage_student_offer'), models.UniqueConstraint(fields=('student', 'rank'), name='unique_stage_student_rank')],
            },
        ),
    ]
