# Generated by Django 5.2.9 on 2026-02-06 14:42

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageApplication',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptee'), ('rejected', 'Rejetee'), ('withdrawn', 'Retiree'), ('confirmed', 'Confirmee')], default='pending', max_length=20, verbose_name='status')),
                ('motivation', models.TextField(help_text="Student's motivation letter or message", verbose_name='motivation')),
                ('cv_url', models.URLField(blank=True, help_text="Link to student's CV", verbose_name='CV URL')),
                ('decision_date', models.DateTimeField(blank=True, help_text='When the application was accepted/rejected', null=True, verbose_name='decision date')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When the student confirmed the assignment', null=True, verbose_name='confirmed at')),
                ('academic_supervisor', models.ForeignKey(blank=True, help_text='Academic supervisor assigned after confirmation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_supervisions', to=settings.AUTH_USER_MODEL, verbose_name='academic supervisor')),
                ('decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_decisions_made', to=settings.AUTH_USER_MODEL, verbose_name='decision by')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='stages.stageoffer', verbose_name='offer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_applications', to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
            options={
                'verbose_name': 'stage application',
                'verbose_name_plural': 'stage applications',
                'ordering': ['-created'],
                'constraints': [models.UniqueConstraint(fields=('student', 'offer'), name='unique_stage_application')],
            },
        ),
    ]
