# Generated by Django 5.2.9 on 2026-03-16 12:00

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_add_stage_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageGrade',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Academic grade on 0-20 scale', max_digits=4, null=True, verbose_name='academic grade')),
                ('academic_grade_comment', models.TextField(blank=True, verbose_name='academic grade comment')),
                ('academic_graded_at', models.DateTimeField(blank=True, null=True, verbose_name='academic graded at')),
                ('company_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Company grade on 0-20 scale', max_digits=4, null=True, verbose_name='company grade')),
                ('company_grade_comment', models.TextField(blank=True, verbose_name='company grade comment')),
                ('company_graded_at', models.DateTimeField(blank=True, null=True, verbose_name='company graded at')),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Average of academic and company grades', max_digits=4, null=True, verbose_name='final grade')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('finalized', 'Finalise')], default='draft', max_length=20, verbose_name='status')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='finalized at')),
                ('academic_graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_academic_grades_given', to=settings.AUTH_USER_MODEL, verbose_name='academic graded by')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='stages.stageapplication', verbose_name='application')),
                ('company_graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_company_grades_given', to=settings.AUTH_USER_MODEL, verbose_name='company graded by')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_grades_finalized', to=settings.AUTH_USER_MODEL, verbose_name='finalized by')),
                ('stage_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='stages.stageperiod', verbose_name='internship period')),
            ],
            options={
                'verbose_name': 'stage grade',
                'verbose_name_plural': 'stage grades',
                'ordering': ['-created'],
            },
        ),
    ]
