#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput

exec gunicorn config.wsgi \
    --bind 0.0.0.0:5000 \
    --chdir=/app \
    --workers 2 \
    --worker-class gthread \
    --threads 16 \
    --timeout 1860 \
    --keep-alive 5 \
    --access-logfile - \
    --error-logfile -
