# Generated by Django 5.2.9 on 2026-01-27 10:25

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TERPeriod',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'TER 2024-2025 S1'", max_length=200, verbose_name='name')),
                ('academic_year', models.CharField(help_text='Format: 2024-2025', max_length=9, verbose_name='academic year')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('open', 'Ouvert'), ('closed', 'Cloture'), ('archived', 'Archive')], default='draft', max_length=20, verbose_name='status')),
                ('group_formation_start', models.DateField(help_text='Date when students can start forming groups', verbose_name='group formation start')),
                ('group_formation_end', models.DateField(help_text='Deadline for group formation', verbose_name='group formation end')),
                ('subject_selection_start', models.DateField(help_text='Date when groups can start selecting subjects', verbose_name='subject selection start')),
                ('subject_selection_end', models.DateField(help_text='Deadline for subject selection/ranking', verbose_name='subject selection end')),
                ('assignment_date', models.DateField(help_text='Date when algorithm runs to assign subjects', verbose_name='assignment date')),
                ('project_start', models.DateField(help_text='Start date for TER projects', verbose_name='project start')),
                ('project_end', models.DateField(help_text='End date for TER projects', verbose_name='project end')),
                ('min_group_size', models.PositiveSmallIntegerField(default=1, verbose_name='minimum group size')),
                ('max_group_size', models.PositiveSmallIntegerField(default=4, verbose_name='maximum group size')),
            ],
            options={
                'verbose_name': 'TER period',
                'verbose_name_plural': 'TER periods',
                'ordering': ['-academic_year', '-created'],
            },
        ),
        migrations.CreateModel(
            name='TERSubject',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('domain', models.CharField(help_text="e.g., 'IA/ML', 'Securite', 'Web', 'Systemes'", max_length=100, verbose_name='domain')),
                ('prerequisites', models.TextField(blank=True, help_text='Required skills or knowledge', verbose_name='prerequisites')),
                ('max_groups', models.PositiveSmallIntegerField(default=1, help_text='Number of groups that can work on this subject', verbose_name='maximum groups')),
                ('status', django_fsm.FSMField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('validated', 'Valide'), ('rejected', 'Rejete')], default='draft', max_length=50, verbose_name='status')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ter_subjects_created', to=settings.AUTH_USER_MODEL, verbose_name='professor')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ter_subjects_supervised', to=settings.AUTH_USER_MODEL, verbose_name='supervisor')),
                ('ter_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='ter.terperiod', verbose_name='TER period')),
            ],
            options={
                'verbose_name': 'TER subject',
                'verbose_name_plural': 'TER subjects',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TERRanking',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.PositiveSmallIntegerField(help_text='1 = most preferred', verbose_name='rank')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ter_rankings', to='groups.group', verbose_name='group')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='ter.tersubject', verbose_name='subject')),
            ],
            options={
                'verbose_name': 'TER ranking',
                'verbose_name_plural': 'TER rankings',
                'ordering': ['group', 'rank'],
                'constraints': [models.UniqueConstraint(fields=('group', 'subject'), name='unique_ter_group_subject'), models.UniqueConstraint(fields=('group', 'rank'), name='unique_ter_group_rank')],
            },
        ),
        migrations.CreateModel(
            name='TERFavorite',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ter_favorites', to=settings.AUTH_USER_MODEL, verbose_name='student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='ter.tersubject', verbose_name='subject')),
            ],
            options={
                'verbose_name': 'TER favorite',
                'verbose_name_plural': 'TER favorites',
                'constraints': [models.UniqueConstraint(fields=('student', 'subject'), name='unique_ter_student_favorite')],
            },
        ),
    ]
