# Generated by Django 5.2.9 on 2026-01-27 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='terperiod',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, help_text='Students registered for this TER period', related_name='enrolled_ter_periods', to=settings.AUTH_USER_MODEL, verbose_name='enrolled students'),
        ),
    ]
