# Generated by Django 5.2.9 on 2026-02-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ter', '0002_add_enrolled_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='tersubject',
            name='max_group_size',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Maximum group size for this subject. Must be <= period max_group_size.', null=True, verbose_name='maximum group size'),
        ),
        migrations.AddField(
            model_name='tersubject',
            name='min_group_size',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Minimum group size for this subject. Must be >= period min_group_size.', null=True, verbose_name='minimum group size'),
        ),
    ]
