# Generated by Django 5.2.9 on 2026-02-05 09:02

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ter', '0003_tersubject_max_group_size_tersubject_min_group_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalancingOperation',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('student_to_group', 'Etudiant vers groupe'), ('merge_groups', 'Fusion de groupes'), ('force_form', 'Formation forcee'), ('force_assign', 'Affectation forcee'), ('revert_assignment', "Annulation d'affectation"), ('move_student', "Deplacement d'etudiant")], max_length=30, verbose_name='operation type')),
                ('details', models.JSONField(default=dict, help_text='Operation details: student_id, source_group_id, target_group_id, similarity_score, etc.', verbose_name='details')),
                ('is_automatic', models.BooleanField(default=False, help_text='True if performed by the balancing algorithm', verbose_name='automatic')),
                ('reason', models.TextField(blank=True, help_text='Explanation for the operation', verbose_name='reason')),
                ('performed_by', models.ForeignKey(blank=True, help_text='User who performed the operation (null for automatic)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balancing_operations', to=settings.AUTH_USER_MODEL, verbose_name='performed by')),
                ('ter_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balancing_operations', to='ter.terperiod', verbose_name='TER period')),
            ],
            options={
                'verbose_name': 'balancing operation',
                'verbose_name_plural': 'balancing operations',
                'ordering': ['-created'],
            },
        ),
    ]
