# Generated by Django 5.2.9 on 2026-02-06 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ter', '0004_add_balancing_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tersubject',
            name='ter_period',
            field=models.ForeignKey(blank=True, help_text='Optional: can be assigned later when submitting for approval', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='ter.terperiod', verbose_name='TER period'),
        ),
    ]
