# Generated by Django 5.2.9 on 2026-02-06 09:04

import backend_django.ter.models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_add_assigned_offer'),
        ('ter', '0005_subject_nullable_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TERDeliverable',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, upload_to=backend_django.ter.models.deliverable_upload_path, verbose_name='file')),
                ('original_filename', models.CharField(max_length=255, verbose_name='original filename')),
                ('content_type', models.CharField(default='application/octet-stream', max_length=100, verbose_name='content type')),
                ('size', models.PositiveIntegerField(default=0, help_text='Size in bytes', verbose_name='file size')),
                ('deliverable_type', models.CharField(choices=[('report', 'Rapport'), ('code', 'Code source'), ('presentation', 'Presentation'), ('other', 'Autre')], default='other', max_length=20, verbose_name='type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_confidential', models.BooleanField(default=False, help_text='If true, only group members and encadrant can access', verbose_name='confidential')),
                ('upload_status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Termine'), ('failed', 'Echec')], default='completed', max_length=20, verbose_name='upload status')),
                ('upload_error', models.TextField(blank=True, help_text='Error message if upload failed', verbose_name='upload error')),
                ('celery_task_id', models.CharField(blank=True, help_text='Task ID for async upload tracking', max_length=255, verbose_name='Celery task ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ter_deliverables', to='groups.group', verbose_name='group')),
                ('ter_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='ter.terperiod', verbose_name='TER period')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ter_deliverables_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'TER deliverable',
                'verbose_name_plural': 'TER deliverables',
                'ordering': ['-created'],
            },
        ),
    ]
