# Generated by Django 5.2.9 on 2026-02-06 09:12

import backend_django.ter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ter', '0006_add_ter_deliverable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terdeliverable',
            name='file',
            field=models.FileField(blank=True, max_length=500, upload_to=backend_django.ter.models.deliverable_upload_path, verbose_name='file'),
        ),
    ]
