# Generated by Django 5.2.9 on 2026-02-06 09:50

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ter', '0007_deliverable_file_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverableAccessLog',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deliverable_filename', models.CharField(help_text='Preserved filename for audit after deliverable deletion', max_length=255, verbose_name='filename')),
                ('deliverable_group_name', models.CharField(blank=True, help_text='Preserved group name for audit', max_length=200, verbose_name='group name')),
                ('user_email', models.EmailField(help_text='Preserved email for audit after user deletion', max_length=254, verbose_name='user email')),
                ('access_type', models.CharField(choices=[('upload', 'Telechargement'), ('download', 'Telechargement'), ('update', 'Modification'), ('delete', 'Suppression'), ('view', 'Consultation')], max_length=20, verbose_name='access type')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional context about the operation', verbose_name='details')),
                ('deliverable', models.ForeignKey(blank=True, help_text='The deliverable that was accessed (null if deleted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='ter.terdeliverable', verbose_name='deliverable')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverable_access_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'deliverable access log',
                'verbose_name_plural': 'deliverable access logs',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['deliverable', '-created'], name='ter_deliver_deliver_1db385_idx'), models.Index(fields=['user', '-created'], name='ter_deliver_user_id_7d33fd_idx'), models.Index(fields=['access_type', '-created'], name='ter_deliver_access__eda739_idx')],
            },
        ),
    ]
