# Generated by Django 5.2.9 on 2026-02-06 10:06

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_add_assigned_offer'),
        ('ter', '0008_add_deliverable_access_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TERGrade',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Grade on 0-20 scale', max_digits=4, null=True, verbose_name='group grade')),
                ('group_grade_comment', models.TextField(blank=True, help_text='Comment explaining the grade', verbose_name='grade comment')),
                ('individual_grading_enabled', models.BooleanField(default=False, help_text='If true, students can opt-in for individual grades', verbose_name='individual grading enabled')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('finalized', 'Finalise')], default='draft', max_length=20, verbose_name='status')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='finalized at')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ter_grades_finalized', to=settings.AUTH_USER_MODEL, verbose_name='finalized by')),
                ('graded_by', models.ForeignKey(help_text='Encadrant who entered the grade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ter_grades_given', to=settings.AUTH_USER_MODEL, verbose_name='graded by')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ter_grade', to='groups.group', verbose_name='group')),
                ('ter_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='ter.terperiod', verbose_name='TER period')),
            ],
            options={
                'verbose_name': 'TER grade',
                'verbose_name_plural': 'TER grades',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewer_token', models.CharField(help_text='Ephemeral token of the reviewer (session may be deleted)', max_length=36, verbose_name='reviewer token')),
                ('contribution_score', models.PositiveSmallIntegerField(help_text='1-5 scale for project contribution', verbose_name='contribution score')),
                ('collaboration_score', models.PositiveSmallIntegerField(help_text='1-5 scale for teamwork and communication', verbose_name='collaboration score')),
                ('technical_skill_score', models.PositiveSmallIntegerField(help_text='1-5 scale for technical abilities', verbose_name='technical skill score')),
                ('comment', models.TextField(blank=True, help_text='Optional qualitative feedback', verbose_name='comment')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='groups.group', verbose_name='group')),
                ('reviewed_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='reviewed student')),
                ('ter_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='ter.terperiod', verbose_name='TER period')),
            ],
            options={
                'verbose_name': 'peer review',
                'verbose_name_plural': 'peer reviews',
                'ordering': ['-created'],
                'constraints': [models.UniqueConstraint(fields=('group', 'reviewer_token', 'reviewed_student'), name='unique_peer_review_per_reviewer_reviewed')],
            },
        ),
        migrations.CreateModel(
            name='PeerReviewSession',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ephemeral_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ephemeral token')),
                ('expires_at', models.DateTimeField(help_text='When this session (and the mapping) will be destroyed', verbose_name='expires at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_review_sessions', to='groups.group', verbose_name='group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_review_sessions', to=settings.AUTH_USER_MODEL, verbose_name='student')),
                ('ter_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_review_sessions', to='ter.terperiod', verbose_name='TER period')),
            ],
            options={
                'verbose_name': 'peer review session',
                'verbose_name_plural': 'peer review sessions',
                'constraints': [models.UniqueConstraint(fields=('ter_period', 'student'), name='unique_peer_review_session_per_student')],
            },
        ),
        migrations.CreateModel(
            name='TERIndividualGrade',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opted_in', models.BooleanField(default=False, verbose_name='opted in')),
                ('opted_in_at', models.DateTimeField(blank=True, null=True, verbose_name='opted in at')),
                ('individual_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Individual grade on 0-20 scale', max_digits=4, null=True, verbose_name='individual grade')),
                ('individual_grade_comment', models.TextField(blank=True, verbose_name='individual grade comment')),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Computed final grade (individual if opted-in, otherwise group)', max_digits=4, null=True, verbose_name='final grade')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_grades', to='ter.tergrade', verbose_name='TER grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ter_individual_grades', to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
            options={
                'verbose_name': 'TER individual grade',
                'verbose_name_plural': 'TER individual grades',
                'constraints': [models.UniqueConstraint(fields=('grade', 'student'), name='unique_ter_individual_grade_per_student')],
            },
        ),
    ]
