# Generated by Django 5.2.9 on 2026-02-06 18:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ter', '0009_add_grading_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='tersubject',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text="Technology tags, e.g., ['Python', 'React', 'PostgreSQL']", size=None, verbose_name='tags'),
        ),
    ]
