# Generated by Django 5.2.9 on 2026-02-07 15:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ter', '0010_add_tags_to_tersubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='tersubject',
            name='taches',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Task list for the project', size=None, verbose_name='taches'),
        ),
    ]
