# Generated by Django 5.2.9 on 2026-02-12 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ter', '0011_add_taches_to_tersubject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='terperiod',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Main responsible for this TER period', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ter_periods_as_responsable', to=settings.AUTH_USER_MODEL, verbose_name='responsable TER'),
        ),
        migrations.AddField(
            model_name='terperiod',
            name='professors',
            field=models.ManyToManyField(blank=True, help_text='Professors/encadrants participating in this TER period', related_name='ter_periods_as_professor', to=settings.AUTH_USER_MODEL, verbose_name='professors'),
        ),
    ]
