# Generated by Django 5.2.9 on 2026-03-16 10:39

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_max_group_size'),
        ('ter', '0012_terperiod_manager_terperiod_professors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TERIndividualRanking',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.PositiveSmallIntegerField(help_text='1 = most preferred', verbose_name='rank')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_rankings', to='groups.group', verbose_name='group')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_rankings', to='ter.tersubject', verbose_name='subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ter_individual_rankings', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'TER individual ranking',
                'verbose_name_plural': 'TER individual rankings',
                'ordering': ['group', 'user', 'rank'],
            },
        ),
        migrations.DeleteModel(
            name='TERFavorite',
        ),
        migrations.AddConstraint(
            model_name='terindividualranking',
            constraint=models.UniqueConstraint(fields=('group', 'user', 'subject'), name='unique_ter_individual_group_user_subject'),
        ),
        migrations.AddConstraint(
            model_name='terindividualranking',
            constraint=models.UniqueConstraint(fields=('group', 'user', 'rank'), name='unique_ter_individual_group_user_rank'),
        ),
    ]
