# Generated by Django 5.2.9 on 2026-03-19 10:32

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ter", "0013_remove_terfavorite_add_terindividualranking"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradingCriterion",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the evaluation criterion",
                        max_length=200,
                        verbose_name="name",
                    ),
                ),
                (
                    "coefficient",
                    models.FloatField(
                        help_text="Weight of this criterion (0.0 to 1.0)",
                        verbose_name="coefficient",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Order for display and drag & drop reordering",
                        verbose_name="display order",
                    ),
                ),
                (
                    "max_score",
                    models.FloatField(
                        blank=True,
                        default=20,
                        help_text="Maximum score for leaf criteria (e.g. 20)",
                        null=True,
                        verbose_name="maximum score",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="ter.gradingcriterion",
                        verbose_name="parent criterion",
                    ),
                ),
                (
                    "ter_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_criteria",
                        to="ter.terperiod",
                        verbose_name="TER period",
                    ),
                ),
            ],
            options={
                "verbose_name": "grading criterion",
                "verbose_name_plural": "grading criteria",
                "ordering": ["order", "created"],
            },
        ),
    ]
