# Generated by Django 5.2.9 on 2026-03-19 15:35

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0004_group_max_group_size"),
        ("ter", "0014_add_grading_criterion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CriterionScore",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        help_text="Score obtained (0 to max_score of the criterion)",
                        verbose_name="score",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Optional comment for this criterion",
                        verbose_name="comment",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="criterion_scores_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="graded by",
                    ),
                ),
                (
                    "grading_criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="ter.gradingcriterion",
                        verbose_name="grading criterion",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterion_scores",
                        to="groups.group",
                        verbose_name="group",
                    ),
                ),
            ],
            options={
                "verbose_name": "criterion score",
                "verbose_name_plural": "criterion scores",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("grading_criterion", "group"),
                        name="unique_score_per_criterion_per_group",
                    )
                ],
            },
        ),
    ]
